version: '3.8'

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - dfsvolume:/app/master
    networks:
      - dfsnetwork

  chunkserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - dfsvolume:/app/chunkserver/
    networks:
      - dfsnetwork
    deploy:
      replicas: 5

networks:
  dfsnetwork:
    driver: bridge

volumes:
  dfsvolume: