services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m helenite.master
    depends_on:
      - redis-master
    ports:
      - "50051:50051"
    volumes:
      - dfsvolume:/app/master
    networks:
      - dfsnetwork

  chunkserver:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m helenite.chunkserver
    depends_on:
      - master
    volumes:
      - dfsvolume:/app/chunkserver/
    networks:
      - dfsnetwork
    deploy:
      replicas: 2

  client:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m helenite.client
    ports:
      - "8000:8000"
    volumes:
      - dfsvolume:/app/client
    networks:
      - dfsnetwork

  redis-client:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - dfsvolume:/app/data-master/
    networks:
      - dfsnetwork


  redis-master:
    image: redis:latest
    volumes:
      - dfsvolume:/app/data-client/
    networks:
      - dfsnetwork


networks:
  dfsnetwork:
    driver: bridge

volumes:
  dfsvolume: