services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m helenite.master
    depends_on:
      - redis-master
    ports:
      - "50051:50051"
    volumes:
      - dfsvolume:/app/master
    networks:
      - dfsnetwork

  chunkserver:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m helenite.chunkserver
    depends_on:
      - master
    volumes:
      - dfsvolume:/app/chunkserver/
    networks:
      - dfsnetwork
    deploy:
      replicas: 2

  redis-master:
    image: redis:latest 
    environment:
      - REDIS_URL=redis://localhost:6379
    volumes:
      - dfsvolume:/app/data/
    networks:
      - dfsnetwork


networks:
  dfsnetwork:
    driver: bridge

volumes:
  dfsvolume: